name: 'Ping Endpoint'
description: 'Ping endpoint until a specific response is returned'
inputs:
  url:
    description: 'URL to ping'
    required: true
  response_field:
    description: 'JSON field to check in the response'
    required: true
  response_value:
    description: 'Expected value of the response field'
    required: true
  interval:
    description: 'Interval between pings in seconds'
    required: true
    default: '10'
  timeout:
    description: 'Timeout in seconds'
    required: true
    default: '900'
runs:
  using: 'composite'
  steps:
    - run: sudo apt-get install jq
      shell: bash
    - run: chmod +x ${{ github.action_path }}/main.sh
      shell: bash
    - run: echo "Inputs ${{ inputs.url }} ${{ inputs.response_field }} ${{ inputs.response_value }} ${{ inputs.interval }} ${{ inputs.timeout }}"
      shell: bash
    - run: ${{ github.action_path }}/main.sh ${{ inputs.url }} ${{ inputs.response_field }} '${{ inputs.response_value }}' ${{ inputs.interval }} ${{ inputs.timeout }}
      shell: bash
